package org.backend.dto.request;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(
        name = "Razorpay Verify Payment Request",
        description = "DTO used for verifying a Razorpay payment by validating the order ID, payment ID, and signature."
)
public class RazorpayVerifyPaymentRequestDTO {

    @Schema(description = "Unique identifier of the Razorpay order", example = "order_DBJOWzybf0sJbb", requiredMode = Schema.RequiredMode.REQUIRED)
    private String razorpayOrderId;

    @Schema(description = "Unique identifier of the Razorpay payment", example = "pay_DBJOuTycf0sJaa", requiredMode = Schema.RequiredMode.REQUIRED)
    private String razorpayPaymentId;

    @Schema(description = "Signature generated by Razorpay to verify payment authenticity", example = "5f3c2b9e6d8a4b7c9f1a2d3e4f5g6h7i", requiredMode = Schema.RequiredMode.REQUIRED)
    private String razorpaySignature;
}
