name: My First GitHub Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "GitHub Actions is working!"



